import numpy as np
na = np.arange(1,17).reshape(4,4)
print(+na[2,3])
print("\n")
print(na[1,1:3])
print("\n")
print(na[1:3,2])
print("\n")
print(na[1:3, 1:3])
print("\n")
print(na[::2,::2])
print("\n")
print(na[:,2])
print("\n")
print(na[1, :])
print("\n")
print(na[:,:])